#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_lang="0.0.1"
  jq -n --arg lang "$ver_lang" '{lang: $lang}'
}

version "$@"
